name: 'Create draft PR'
description: 'Create draft Pull Request'
inputs:
  title:
    description: 'Title of PR'
    required: true
  branch-prefix:
    description: 'Development branch prefix'
    required: true
outputs:
  pr-number:
    description: PR number
    value: ${{ steps.create-draft-pr.outputs.pr-number }}
runs:
  using: 'composite'
  steps:
    - id: create-draft-pr
      run: |
        PR_BRANCH=${{ inputs.branch-prefix }}/$(date +%s)
        COMMIT_MSG="${{ inputs.title }} ($(date -I))."
        git checkout -b ${PR_BRANCH}
        git config user.name github-actions[bot]
        git config user.email 41828287+github-actions[bot]@users.noreply.github.com
        git add .
        git commit --allow-empty -m "${COMMIT_MSG}"
        git push origin ${PR_BRANCH}
        PR_NUMBER=$( gh pr create -d -B main -f  | grep -o '[^/]*$' )
        echo "Created draft pull request #${PR_NUMBER}."
      shell: bash
