name: Mock Auto Merge

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  empty-step:
    name: Empty Step
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: echo "This is a no-op workflow to trigger other workflows."

  auto-merge-hash:
    name: Merge Hash
    runs-on: ubuntu-latest
    needs: empty-step
    if: ${{ github.event_name == 'pull_request' && startsWith(github.head_ref, 'pr-update/') }}
    env:
      PR_NUM: ${{ github.event.number }}
    steps:
      - name: Auto Merge PR
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = parseInt("${{ env.PR_NUM }}");
            // Merge the PR
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              merge_method: 'squash'
            });
